import type { Metadata } from 'next'
import { Inter, Philosopher } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import SmoothScroll from '@/components/SmoothScroll'
import Image from 'next/image'
import { AuthProvider } from '@/app/context/AuthContext'
import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const philosopher = Philosopher({
  variable: '--font-philosopher',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${philosopher.variable} h-full antialiased`}>
      <body className="relative flex min-h-full w-full flex-col">
        <AuthProvider>
          <Navbar />
          <SmoothScroll>
            <main className="w-full">{children}</main>
            <Footer />
            <Image
              src="/bg-strip.png"
              alt=""
              width={3120}
              height={5800}
              className="absolute inset-0 top-80 z-[9] h-full"
            />
          </SmoothScroll>
        </AuthProvider>
      </body>
    </html>
  )
}
